######################################################################
#
# File name : voter_tb.udo
# Created on: Wed Mar 26 09:49:31 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
