######################################################################
#
# File name : voter_plus_tb_wave.do
# Created on: Mon Apr 07 12:33:14 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
