######################################################################
#
# File name : voter_plus_tb_compile.do
# Created on: Sun Apr 13 14:07:42 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modelsim_dlx64_10.6c\\win64pe\\vlib modelsim_lib/work
D:\\modelsim_dlx64_10.6c\\win64pe\\vlib modelsim_lib/msim

D:\\modelsim_dlx64_10.6c\\win64pe\\vlib modelsim_lib/msim/xil_defaultlib

D:\\modelsim_dlx64_10.6c\\win64pe\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\modelsim_dlx64_10.6c\\win64pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../../project_2.srcs/sources_1/new/voter_plus.v" \
"../../../../project_2.srcs/sim_1/new/voter_plus_tb.v" \


# compile glbl module
D:\\modelsim_dlx64_10.6c\\win64pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

