webtalk_init -webtalk_dir C:/Users/26041/Desktop/Math Logic/Projects/project_4/project_4.sim/sim_1/behav/xsim/xsim.dir/top_plus_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Apr 18 00:04:59 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ae6d5c6b-be79-4e9d-a478-25f01b956dc5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "82617ca958074711aa2b1ddb5dafc22e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i7-13700H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2918 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "40 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8240_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2653377507 -regid "" -xml C:/Users/26041/Desktop/Math Logic/Projects/project_4/project_4.sim/sim_1/behav/xsim/xsim.dir/top_plus_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/26041/Desktop/Math Logic/Projects/project_4/project_4.sim/sim_1/behav/xsim/xsim.dir/top_plus_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/26041/Desktop/Math Logic/Projects/project_4/project_4.sim/sim_1/behav/xsim/xsim.dir/top_plus_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
